[package]
name = "GameEngine2D"
version = "0.1.0"
authors = ["Ariel Keselman <skariel@gmail.com>"]

[dependencies]
glium = "*"
time = "*"
scoped_threadpool = "*"
num_cpus = "*"

# [dependencies.clippy]
# git = "https://github.com/Manishearth/rust-clippy.git"
